import React, {Component} from 'react';
import {
  View,
  Alert
} from 'react-native';

import Spinner from 'react-native-loading-spinner-overlay';

import ListFestival from '../component/ListFestival';
import ErrorScreen from '../component/ErrorScreen';

import ActionButton from 'react-native-action-button';

import * as firebase from 'firebase';

import { Key } from '../config/Key';

var firebaseApp = firebase.initializeApp(Key.keys);



/* 
    --- Key.keys generated by Firebase (./src/config/config.js) ---
    export class Key {
      static keys = {
        apiKey: "API_KEY",
        authDomain: "AUTH_DOMAIN",
        databaseURL: "DATABASE_URL",
        storageBucket: "STORAGE_BUCKET"
      }
    }
*/

export default class ListFestivalView extends Component {

  constructor(props) {
    super(props);

    this.state = {
      loading: true,
      visible: false,
      network: true
    };

    this.itemsRef = firebaseApp.database().ref();

        this._addItem = this._addItem.bind(this);

  }

  componentDidMount() {
    this.setState({
      visible: !this.state.visible
    });
    this.listenForItems(this.itemsRef);
  }


  listenForItems(itemsRef) {
    itemsRef.on('value', (snap) => {

      var items = [];
      snap.forEach((child) => {
        items.push({
          data: child.val()
        });
        console.log('Items ref: ',this.itemsRef);
      });

      this.setState({
        loading: false,
        dataSource: items
      });
    });

  }

  _addItem() {
    Alert.alert(
      'Add New Item',
      null,
      [
        {
          text: 'Add',
          onPress: (text) => {
            this
            .itemsRef
            .child("festivals")
            .child('Test')
            .set({
              name: 'Film',
              value: 'FF'
            })
          }
        },
      ],
      'plain-text'
    );
  }

  render() {
    if (this.state.loading) {
      return (
        <View style={{flex: 1}}>
          <Spinner visible={this.state.visible}/>
        </View>
      );
    }
    else if ((!this.state.loading) && (!this.state.network)) {
      return (
        <ErrorScreen />
      );
    }
    else {
      return (
        <View>
        <ListFestival data={this.state.dataSource[0].data} navigator={this.props.navigator}/>
        <ActionButton buttonColor="rgba(231,76,60,1)" title="Add" onPress={this._addItem}></ActionButton>
        </View>
      );
    }
  }
}